### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by SteMasoli** [dbbs-lab/glia#44]
pip3 install nrn-glia

```
Defaulting to user installation because normal site-packages is not writeable
Collecting nrn-glia
  Using cached nrn_glia-0.5.1-py3-none-any.whl (32 kB)
Collecting nrn-patch>=3.0.0b0
  Using cached nrn_patch-4.0.0a4-py3-none-any.whl (22 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nrn-glia) (59.6.0)
Requirement already satisfied: packaging>=19.0 in /usr/lib/python3/dist-packages (from nrn-glia) (21.3)
Collecting errr
  Using cached errr-1.2.0-py3-none-any.whl (5.9 kB)
Requirement already satisfied: appdirs in /usr/lib/python3/dist-packages (from nrn-glia) (1.4.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from nrn-glia) (2.25.1)
Collecting nrn-glia[neuron]==4.0.0a4
  Using cached nrn_glia-4.0.0a4-py3-none-any.whl (33 kB)
Requirement already satisfied: NEURON>=8.0 in /home/bremen/.local/lib/python3.10/site-packages (from nrn-patch>=3.0.0b0->nrn-glia) (8.2.2)
Requirement already satisfied: numpy>=1.21.0 in /home/bremen/.local/lib/python3.10/site-packages (from nrn-patch>=3.0.0b0->nrn-glia) (1.23.4)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    return _build_result(state)
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in _build_result
    if not _has_route_to_root(state.criteria, key, all_keys, connected):
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  [Previous line repeated 986 more times]
  File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 400, in _has_route_to_root
    for p in criteria[key].iter_parent():
RecursionError: maximum recursion depth exceeded
```

**Comment by Helveg** [comment]
From the error log it seems the error comes from `pip/_internal/cli`, `pip` seems to be running into some Glia unrelated problems. 

1. Do you have this issue only with the `nrn-glia` package?
2. Do you have the issue on other machines?
3. I see you are using `/usr/lib/python3/dist-packages`, since [PEP668 ](https://peps.python.org/pep-0668/) it is more or less officially forbidden to install into such "externally managed" system Pythons, and you should always use a virtual environment. Does the problem still occur if you use a virtual environment?

**Comment by SteMasoli** [comment]
>     1. Do you have this issue only with the `nrn-glia` package?
Tried to install/upgrade other packages and there were no errors.

>     2. I see you are using `/usr/lib/python3/dist-packages`, since [PEP668 ](https://peps.python.org/pep-0668/) it is more or less officially forbidden to install into such "externally managed" system Pythons, and you should always use a virtual environment. Does the problem still occur if you use a virtual environment?
Tried in a virtual env and the response is the same.

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    return _build_result(state)
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in _build_result
    if not _has_route_to_root(state.criteria, key, all_keys, connected):
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 408, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  [Previous line repeated 986 more times]
  File "/home/bremen/test_glia/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 400, in _has_route_to_root
    for p in criteria[key].iter_parent():
RecursionError: maximum recursion depth exceeded
```


>     3. What version is your `pip`? Does the error occur if you update to the latest version of `pip`?
Latest, same issue.
 
>     4. Do you have the issue on other machines?
Yes. Just tested it on my desktop computer which have the same distro (Mint 21) with the latest updates.

**Comment by Helveg** [comment]
Hmm, I'm not sure what to do here, after a quick Google there seem to be several variaties of `pip` bugs that reach the maximum recursion depth; I'd open an issue on the `pip` repository and see what they recommend.

**Comment by Helveg** [comment]
Can you try to `pip install "nrn-glia>=4.0.0a0"` instead? Does that work?

**Comment by SteMasoli** [comment]
This worked. Thank you.

**Comment by Helveg** [comment]
Try to `pip install dbbs-catalogue`. Carefully read whether this perhaps installs another version of glia again.

**Comment by SteMasoli** [comment]
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dbbs-catalogue in /usr/local/lib/python3.10/dist-packages/dbbs_catalogue-0.0.5-py3.10.egg (0.0.5)
Requirement already satisfied: nrn-glia>=0.4 in ./.local/lib/python3.10/site-packages (from dbbs-catalogue) (4.0.0a4)
Requirement already satisfied: appdirs in ./.local/lib/python3.10/site-packages (from nrn-glia>=0.4->dbbs-catalogue) (1.4.4)
Requirement already satisfied: errr>=1.2.0 in ./.local/lib/python3.10/site-packages (from nrn-glia>=0.4->dbbs-catalogue) (1.2.0)
```
Even with --upgrade does not change.

**Comment by Helveg** [comment]
Probably resolved?
